In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
import config

from IPython.display import HTML

### Numerically propagate Newtons Gravity model for many particles

In [84]:
def init_r(D, n):
    r = np.random.normal(loc = D, scale = D/4, size = n)
    thetas = np.random.rand(n)*2*np.pi
    
    rs = np.zeros((n,2))
    rs[:,0] = r*np.cos(thetas)
    rs[:,1] = r*np.sin(thetas)
    return rs

def init_v(r, v):
    
    rn = np.zeros((len(r), 3))
    rn[:,:2] = r
    
    zs = np.zeros(rn.shape)
    zs[:,2] = v
    
    return np.cross(zs,rn)[:,:2]

def init_reset(D,V, n = 100):
    r = init_r(D, n) #np.random.rand(8,2)*10 #np.array([[0.,-1.], [1.,0.], [0.,1.], [-1.,0]])
    v = init_v(r, V) 
    a = np.zeros((len(r), len(r[0])))
    F = np.zeros((len(r), len(r[0])))
    config.masses_ = np.linspace(.1, 100, len(r))*2 #np.array([10000., 1]) #
    #config.masses_[0] = 1000
    #r[0] = [0,0]
    #v[0] = [0,0]
    
    dt = .01
    nframes = 1000
    config.mask_ = np.zeros(n).astype(bool)
    config.r_ = np.ma.array(r, mask=False)
    config.v_ = np.ma.array(v, mask=False)
    config.a_ = np.ma.array(a, mask=False)
    config.F_ = np.ma.array(F, mask=False)
    config.dir_ij_arr_ = np.ma.zeros((len(r), len(r), len(r[0])))
    config.collision_threshold_ = 1.
    return dt, nframes
    
dt, nframes = init_reset(3, 1, n = 10)    

In [85]:
def dir_ij():
    """
    Update the direction matrix from each particle to every other particle
    """
    idxs = np.where(~config.r_.mask[:,0])[0]
    rsubst = config.r_[idxs].copy()
    for i,j in enumerate(idxs):
        config.r_.mask[j] = True
        config.dir_ij_arr_[j] = config.r_ - rsubst[i]
        config.r_.mask[j] = False
    

def mask_all():
    
    config.r_.mask[:,:] = config.mask_[:,np.newaxis]
    config.v_.mask[:,:] = config.mask_[:,np.newaxis]
    config.a_.mask[:,:] = config.mask_[:,np.newaxis]
    config.F_.mask[:,:] = config.mask_[:,np.newaxis]
    config.dir_ij_arr_.mask[:,:,:] = config.mask_[np.newaxis,:,np.newaxis]
    
def Forces():
    """
    Calculate the gravitational Force on each particle due to other particles
    
    returns
    -------
    Forces : Matrix with force on particle i on i:th row
    """
    dir_ij()
    
    norms = np.linalg.norm(config.dir_ij_arr_, axis = 2, keepdims = True) #*masses
    norms = np.ma.array(norms, mask = config.dir_ij_arr_.mask[:,:,:1])
    
    collision_idxs = np.transpose(np.where(norms < config.collision_threshold_)).astype(int)

    firstSmaller = config.masses_[collision_idxs[:,0]] < config.masses_[collision_idxs[:,1]]
    annihilate_idxs = collision_idxs[firstSmaller,0]
    grow_bigger_idxs = collision_idxs[firstSmaller,1]
    
    # Update the masses The same is required for velocities!!
    config.masses_[grow_bigger_idxs] += config.masses_[annihilate_idxs]
    config.mask_[annihilate_idxs] = True
    
    #print(annihilate_idxs)
    # mask everything since particles have vanished
    mask_all()
    
    masses_arr = np.tile(config.masses_, len(config.r_)).reshape(config.dir_ij_arr_.shape[:2] + (1,))
    
    #print(config.dir_ij_arr_[1,:,:])
    
    dirs_m = config.dir_ij_arr_/norms*masses_arr
    config.F_ = np.dot(np.diag(config.masses_), (dirs_m/norms**2).sum(axis = 1))
    return config.F_

#### From Forces calculate the everything needed :) 

In [86]:
def update_positions_and_velocities(): #r, v, dt = .01):
    
    config.a_ = np.dot(np.diag(1/config.masses_), Forces())
    config.r_ += dt*config.v_ + .5*config.a_*dt**2
    config.v_ += config.a_*dt
    
update_positions_and_velocities()    

[[[--]
  [4.999457056171169]
  [9.1595304815344]
  [4.230866296475604]
  [5.994120193263107]
  [7.336605809077417]
  [2.982234605621031]
  [6.587675220083214]
  [7.161625222848994]
  [7.761551400683266]]

 [[4.999457056171169]
  [--]
  [5.632219006162441]
  [0.7686689553629756]
  [1.294082151784938]
  [6.130854853628136]
  [2.24527041264005]
  [4.270768498204616]
  [5.837502775339486]
  [3.3810316880762863]]

 [[9.1595304815344]
  [5.632219006162441]
  [--]
  [6.049041907690881]
  [6.10560819452503]
  [3.769076866254167]
  [6.388097286455673]
  [2.7819322293701028]
  [3.599090054512522]
  [2.5554141914288127]]

 [[4.230866296475604]
  [0.7686689553629756]
  [6.049041907690881]
  [--]
  [1.9159631375284056]
  [6.079020259736918]
  [1.5482246560558794]
  [4.35219369560965]
  [5.795480074877405]
  [3.966358283773273]]

 [[5.994120193263107]
  [1.294082151784938]
  [6.10560819452503]
  [1.9159631375284056]
  [--]
  [7.200912075903814]
  [3.4637561825064553]
  [5.253952806055508]
  [6.90296

#### Animate using pyplot

In [7]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

rnorm = 15
dt, nframes = init_reset(rnorm, .25, 200)
fig, ax = plt.subplots(figsize = (8,8))

scat = plt.scatter([], [], marker = '.', animated=True)

def data_gen():
    cnt = 0
    while cnt < nframes:
        print(cnt)
        update_positions_and_velocities()
        cnt += 1
        yield config.r_



def init():
    plt.axis('equal')
    plt.axis('off')
    ax.set_xlim(-10*rnorm,10*rnorm)
    ax.set_ylim(-10*rnorm,10*rnorm)

    return scat,

def update(data):
    update_positions_and_velocities()
    
    #print((~config.r_.mask[:,0]).sum())
    scat.set_offsets(config.r_)
    return scat,

ani = FuncAnimation(fig, update, nframes,
                    init_func=init, blit=True, 
                    interval = dt*1000)
HTML(ani.to_html5_video())
#plt.clf()